---
- name: Deploy Flask Application
  hosts: all
  become: yes
  vars:
    app_dir: "project"
    python_version: "3.12.4"
    flask_requirements: "requirements.txt"

  tasks:
    - name: Update and upgrade packages
      yum:
        name: "*"
        state: latest

    - name: Install dependencies
      yum:
        name:
          - git
          - python3
          - python3-pip
        state: present

    - name: Copy shell script to remote server
      copy:
        src: home/ec2-user/flask.sh
        dest: home/ec2-user/flask.sh
        mode: 0755

    - name: Run shell script on remote server
      shell: sh home/ec2-user/flask.sh
