name: Flask App

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.4"
    - name: Exports
      run: |
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
    - name: Run unittests
      run: python tests.py


