name: Flask App

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12.4
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Exports
      run: |
        source .venv/bin/activate
        export FLASK_APP=.
        export FLASK_DEBUG=1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
    - name: Run unittests
      run: python3 tests.py


